In [23]:
# imports
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [24]:
class WineDataset(Dataset):
  def __init__(self):
    # data loading
    xy = np.loadtxt('./wine.csv', delimiter=",", dtype=np.float32, skiprows=1)
    self.x = torch.from_numpy(xy[: , 1:])
    self.y = torch.from_numpy(xy[: , [0]]) # size of (n_samples, 1) => helps later
    self.num_samples = xy.shape[0]
    

  def __getitem__(self, index):
    return self.x[index], self.y[index]

  def __len__(self):
    return self.num_samples

In [21]:
dataset = WineDataset()
first_data = dataset[0]
features, labels = first_data

print(features)
print(labels)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])
tensor([1.])


In [26]:
dataset = WineDataset()
dataloader = DataLoader(dataset=dataset, batch_size=4, shuffle=True, num_workers=2)

dataiter = iter(dataloader)
data = dataiter.__next__()

features, labels = data
print(features)
print(labels)

tensor([[1.2640e+01, 1.3600e+00, 2.0200e+00, 1.6800e+01, 1.0000e+02, 2.0200e+00,
         1.4100e+00, 5.3000e-01, 6.2000e-01, 5.7500e+00, 9.8000e-01, 1.5900e+00,
         4.5000e+02],
        [1.2700e+01, 3.8700e+00, 2.4000e+00, 2.3000e+01, 1.0100e+02, 2.8300e+00,
         2.5500e+00, 4.3000e-01, 1.9500e+00, 2.5700e+00, 1.1900e+00, 3.1300e+00,
         4.6300e+02],
        [1.2250e+01, 1.7300e+00, 2.1200e+00, 1.9000e+01, 8.0000e+01, 1.6500e+00,
         2.0300e+00, 3.7000e-01, 1.6300e+00, 3.4000e+00, 1.0000e+00, 3.1700e+00,
         5.1000e+02],
        [1.2870e+01, 4.6100e+00, 2.4800e+00, 2.1500e+01, 8.6000e+01, 1.7000e+00,
         6.5000e-01, 4.7000e-01, 8.6000e-01, 7.6500e+00, 5.4000e-01, 1.8600e+00,
         6.2500e+02]])
tensor([[2.],
        [2.],
        [2.],
        [3.]])


In [28]:
# training loop
num_epochs = 2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/4)
print(total_samples, n_iterations)


for epoch in range(num_epochs):
  for i, (inputs,labels) in enumerate(dataloader):
    # forward pass, backward pass, update
    if (i+1)%5 == 0: 
      print(f'epoch: {epoch+1}/{num_epochs}, step {i+1}/{n_iterations}, inputs {inputs.shape}')

178 45
epoch: 1/2, step 5/45, inputs torch.Size([4, 13])
epoch: 1/2, step 10/45, inputs torch.Size([4, 13])
epoch: 1/2, step 15/45, inputs torch.Size([4, 13])
epoch: 1/2, step 20/45, inputs torch.Size([4, 13])
epoch: 1/2, step 25/45, inputs torch.Size([4, 13])
epoch: 1/2, step 30/45, inputs torch.Size([4, 13])
epoch: 1/2, step 35/45, inputs torch.Size([4, 13])
epoch: 1/2, step 40/45, inputs torch.Size([4, 13])
epoch: 1/2, step 45/45, inputs torch.Size([2, 13])
epoch: 2/2, step 5/45, inputs torch.Size([4, 13])
epoch: 2/2, step 10/45, inputs torch.Size([4, 13])
epoch: 2/2, step 15/45, inputs torch.Size([4, 13])
epoch: 2/2, step 20/45, inputs torch.Size([4, 13])
epoch: 2/2, step 25/45, inputs torch.Size([4, 13])
epoch: 2/2, step 30/45, inputs torch.Size([4, 13])
epoch: 2/2, step 35/45, inputs torch.Size([4, 13])
epoch: 2/2, step 40/45, inputs torch.Size([4, 13])
epoch: 2/2, step 45/45, inputs torch.Size([2, 13])


In [30]:
#
import torchvision.datasets as datasets

# Create an instance of the MNIST dataset
mnist_dataset = datasets.MNIST(root="./", train=True, download=True)

print(mnist_dataset)


100%|██████████| 9912422/9912422 [00:00<00:00, 100047432.97it/s]


Extracting ./MNIST/raw/train-images-idx3-ubyte.gz to ./MNIST/raw



100%|██████████| 28881/28881 [00:00<00:00, 84297629.66it/s]


Extracting ./MNIST/raw/train-labels-idx1-ubyte.gz to ./MNIST/raw



100%|██████████| 1648877/1648877 [00:00<00:00, 26824703.46it/s]


Extracting ./MNIST/raw/t10k-images-idx3-ubyte.gz to ./MNIST/raw



100%|██████████| 4542/4542 [00:00<00:00, 2743846.86it/s]


Extracting ./MNIST/raw/t10k-labels-idx1-ubyte.gz to ./MNIST/raw

Dataset MNIST
    Number of datapoints: 60000
    Root location: ./
    Split: Train


In [14]:
np.set_printoptions(threshold=np.inf) # print out np array without truncation
xy = np.loadtxt('./wine.csv', delimiter=",", dtype=np.float32, skiprows=1)
print(xy)

[[1.000000e+00 1.423000e+01 1.710000e+00 2.430000e+00 1.560000e+01
  1.270000e+02 2.800000e+00 3.060000e+00 2.800000e-01 2.290000e+00
  5.640000e+00 1.040000e+00 3.920000e+00 1.065000e+03]
 [1.000000e+00 1.320000e+01 1.780000e+00 2.140000e+00 1.120000e+01
  1.000000e+02 2.650000e+00 2.760000e+00 2.600000e-01 1.280000e+00
  4.380000e+00 1.050000e+00 3.400000e+00 1.050000e+03]
 [1.000000e+00 1.316000e+01 2.360000e+00 2.670000e+00 1.860000e+01
  1.010000e+02 2.800000e+00 3.240000e+00 3.000000e-01 2.810000e+00
  5.680000e+00 1.030000e+00 3.170000e+00 1.185000e+03]
 [1.000000e+00 1.437000e+01 1.950000e+00 2.500000e+00 1.680000e+01
  1.130000e+02 3.850000e+00 3.490000e+00 2.400000e-01 2.180000e+00
  7.800000e+00 8.600000e-01 3.450000e+00 1.480000e+03]
 [1.000000e+00 1.324000e+01 2.590000e+00 2.870000e+00 2.100000e+01
  1.180000e+02 2.800000e+00 2.690000e+00 3.900000e-01 1.820000e+00
  4.320000e+00 1.040000e+00 2.930000e+00 7.350000e+02]
 [1.000000e+00 1.420000e+01 1.760000e+00 2.450000e+00 1