# Tensor Basics


In [1]:
# in Pytorch, everything is a tensor of varying dimensions (1D tensor, 2D tensor, etc.)
import torch

In [5]:
# x = torch.empty(1) # just an empty tensor - like a scalar value
# x = torch.empty(3) # like a 1D vector with 3 elements
x = torch.empty(2,3) # 2x3 tensor (matrix)
print(x)

tensor([[3.8453e-34, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44]])


In [6]:
x = torch.rand(2,2)
print(x) # tensor with random values

tensor([[0.0338, 0.8626],
        [0.3150, 0.4333]])


In [9]:
# can specify with ones or zeros
x = torch.ones(2,2)
print(x)
y = torch.zeros(2,2)
print(y)

print(x.dtype) # by default our values have a torch.float32 datatype

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
torch.float32


In [11]:
x = torch.ones(2,2, dtype= torch.int) # we can use the dtype parameter to specify the data type of our values
y = torch.ones(2,2, dtype= torch.double)
z = torch.ones(2,2, dtype= torch.float16)  

print(x)
print(y)
print(z)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


In [12]:
# We can also construct a tensor from data, like a Python list
x = torch.tensor([1,2,3,4,5])
print(x)

tensor([1, 2, 3, 4, 5])



# Basic Operations

In [16]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)
print(y)

z = x + y
print(z) # element-wise addition is done here

z_2 = torch.add(x,y) # torch.add() is another way to add two tensors
print(z_2)


# We can also do an in-place addition:
y.add_(x) # This will modify our y by adding all elements of x to y
print(y)

# In Pytorch, every function with a trailing underscore (such as add_() above) will do an in place operation,
# thus modifying the variable it is applied on

# We can also do z = x - y   or z = torch.sub(x,y)
# To multiply we can do z = x*y  or z = torch.mul(x,y)

tensor([[0.4841, 0.8316],
        [0.3370, 0.1803]])
tensor([[0.8445, 0.3616],
        [0.6615, 0.4312]])
tensor([[1.3286, 1.1932],
        [0.9985, 0.6115]])
tensor([[1.3286, 1.1932],
        [0.9985, 0.6115]])
tensor([[1.3286, 1.1932],
        [0.9985, 0.6115]])


In [21]:
# We can also do slicing operations on tensors, like we do with numpy arrays

x = torch.rand(5,3)
print(x)


print(x[:1])    # all rows but only col 0
print(x[1:])    # all columns, just first row
print(x[1,1])   # the one at index (1,1)

# if we have a tensor with one element, we can call the .item() method to get the actual value
print(x[1,1].item())

tensor([[0.9627, 0.9769, 0.0632],
        [0.8108, 0.0534, 0.6111],
        [0.1041, 0.2638, 0.9335],
        [0.0791, 0.2503, 0.2257],
        [0.7498, 0.8760, 0.1399]])
tensor([[0.9627, 0.9769, 0.0632]])
tensor([[0.8108, 0.0534, 0.6111],
        [0.1041, 0.2638, 0.9335],
        [0.0791, 0.2503, 0.2257],
        [0.7498, 0.8760, 0.1399]])
tensor(0.0534)
0.05343818664550781
tensor([[0.4991, 0.3225, 0.5195, 0.5421],
        [0.6133, 0.6155, 0.5270, 0.8387],
        [0.2724, 0.4646, 0.5342, 0.0812],
        [0.1582, 0.2616, 0.4066, 0.6171]])


In [27]:
# Reshape a tensor:
x = torch.rand(4,4)
print(x)

print("   ")

y = x.view(16) # .view() is used to reshape the tensor - num of elements should still remain the same
print(y) # so now we just have a 1D vector with 16 elements all in this one dimension

print("   ")

z = x.view(-1,8) # here we are only specifying the second dimension and with '-1', Pytorch will automatically determine the right size
print(z)
print(z.size())

tensor([[0.0836, 0.2379, 0.3597, 0.5504],
        [0.0985, 0.7130, 0.2364, 0.3403],
        [0.3458, 0.5428, 0.5341, 0.2795],
        [0.9963, 0.5492, 0.6815, 0.7845]])
   
tensor([0.0836, 0.2379, 0.3597, 0.5504, 0.0985, 0.7130, 0.2364, 0.3403, 0.3458,
        0.5428, 0.5341, 0.2795, 0.9963, 0.5492, 0.6815, 0.7845])
   
tensor([[0.0836, 0.2379, 0.3597, 0.5504, 0.0985, 0.7130, 0.2364, 0.3403],
        [0.3458, 0.5428, 0.5341, 0.2795, 0.9963, 0.5492, 0.6815, 0.7845]])
torch.Size([2, 8])


In [36]:
# Converting between numpy arrays and tensors
import numpy as np

a = torch.ones(5)
print(a)
print(a.type)

print("       ")

b = a.numpy()
print(b)
print(type(b))

print("       ")

# !! If the tensor is on the CPU and not the GPU, then both objects will share the same memory location, which means that
# if we were to change one, we would also change the other

# let's show the point above:
a.add_(1) # in place addition to add a 1 to each element
print(a)
print(b)  # we can see that even b (the numpy array version of 'a') was modified from the modification of 'a' (our tensor) 
          # since they both point to the same memory location!

print("       ")

#  lets do it the other way: converting from numpy array to torch tensor

a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

print("       ")

# We show the point above once again - since memory is shared, modification in one also modifies the other
a += 1
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
<built-in method type of Tensor object at 0x7fc67b172a40>
       
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
       
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
       
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
       
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
# need cuda toolkit to use GPU
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device = device) # to create a tensor and put it on the GPU

  y = torch.ones(5)
  y = y.to(device) # to move it to our GPU device

  z = x + y # if we now do this operation it will be performed on the GPU and will probably be much faster as a result
  
  z.numpy() # but this will return an error because numpy can only handle CPU tensors (cannot convert a GPU tensor back to numpy)
  z = z.to("cpu") # so we should move it back to the CPU

In [37]:
# We often see the following:
x = torch.ones(5, requires_grad=True) # by default 'requires_grad=False'
print(x)

# this tells Pytorch that we will need to calculate the gradients for this tensor later in our optimization steps
# so whenever we have a variable in our model that we need to optimize, we need the gradients, so we should specify
# 'requires_grad = True'

tensor([1., 1., 1., 1., 1.], requires_grad=True)
